data_root : data

wesad_data_ingestion:
  data_source_path: data/raw/WESAD
  data_target_path: data/processed/WESAD

signal_processing:
  bvp_filter_low: 0.7
  bvp_filter_high: 3.7
  eda_filter_low: 0.05
  eda_filter_high: 1.0
  acc_threshold: 66.0
  jerking_threshold: 2.0
  motion_window: 32
  overlap: 30 # window_size // 2
  quality_threshold: 0.85
  physiological_ranges:
    bvp_min: -1.0
    bvp_max: 1.0
    eda_min: 4.0
    eda_max: 6.0
    temp_min: 35.0
    temp_max: 37.0

preprocessing:
  processed_data_path: data/processed/WESAD
  temp_baseline : 35.0
  artifact_threshold : 0.3
  processed_data_target_path: data/signal_processed

feature_extraction:
  sampling_rate: 4
  hrv_features: true
  time_domain_features: true
  frequency_domain_features: true
  motion_features: true
  eda_features: true 
  quality_threshold: 0.80
  temperature_features: true
  target_path : data

